name: ðŸš€ Deploy to Strato via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”„ Checkout Repository
        uses: actions/checkout@v4

      - name: ðŸ“¤ Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          ssh_private_key: ""
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: '/www/'
          sftp_only: true
          delete_remote_files: false
